version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/installapache.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/restartapache.sh
      timeout: 300
      runas: root
